name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pandas

    - name: Get flake8 path
      id: get_flake8_path
      run: |
        which flake8
      # save the output to an output variable
      id: flake8_path

    - name: Lint with flake8
      run: |
        # use the full path to the flake8 command
        ${{ steps.get_flake8_path.outputs.flake8_path }} . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ${{ steps.get_flake8_path.outputs.flake8_path }} . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
