name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pandas

    - name: Get flake8 path
      run: which flake8
      id: get_flake8_path

    - name: Lint with flake8
      run: |
        # use the full path to the flake8 command
        ${{ runner.tools.docker.available ? 'docker-compose' : 'sh' }} -c "$(cat .github/workflows/flake8.sh)|FLAKE8_PATH=$(cat ${{ steps.get_flake8_path.outputs.flake8_path }})"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ${{ runner.tools.docker.available ? 'docker-compose' : 'sh' }} -c "$(cat .github/workflows/flake8.sh)|FLAKE8_PATH=$(cat ${{ steps.get_flake8_path.outputs.flake8_path }})|flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics"

    - name: Test with pytest
      run: |
        pytest
